export {
  evaluateFailureContainment,
  transitionCircuit,
  transitionKillSwitch,
} from './failure-containment.js';
export type {
  CancellationDisposition,
  CircuitEvent,
  CircuitSnapshot,
  CircuitState,
  CircuitTransitionReason,
  CircuitTransitionRequest,
  CircuitTransitionResult,
  DependencyHealth,
  EvaluateFailureContainmentRequest,
  ExecutionContainmentPhase,
  FailureContainmentReason,
  FailureContainmentResult,
  FailureContainmentSnapshot,
  KillSwitchCommand,
  KillSwitchSnapshot,
  KillSwitchState,
  KillSwitchTransitionReason,
  KillSwitchTransitionRequest,
  KillSwitchTransitionResult,
  NonAuthoritativeExecutionSignals,
  RecoveryGate,
} from './types.js';
