export {
  evaluateFailureContainment,
  transitionCircuit,
  transitionKillSwitch,
} from './failure-containment.js';
export {
  createInMemoryW03LeaseExecutor,
  createW03HalfOpenProbeFenceAdapter,
} from './probe-fence.js';
export type {
  AcquireProbeFenceRequest,
  AcquireProbeFenceResult,
  CancellationDisposition,
  CircuitEvent,
  CircuitSnapshot,
  CircuitState,
  CircuitTransitionReason,
  CircuitTransitionRequest,
  CircuitTransitionResult,
  DependencyHealth,
  EvaluateFailureContainmentRequest,
  ExecutionContainmentPhase,
  FailureContainmentReason,
  FailureContainmentResult,
  FailureContainmentSnapshot,
  HalfOpenProbeFencePort,
  HeartbeatProbeFenceRequest,
  HeartbeatProbeFenceResult,
  KillSwitchCommand,
  KillSwitchSnapshot,
  KillSwitchState,
  KillSwitchTransitionReason,
  KillSwitchTransitionRequest,
  KillSwitchTransitionResult,
  NonAuthoritativeExecutionSignals,
  ProbeFenceAcquireReason,
  ProbeFenceHeartbeatReason,
  ProbeFenceReleaseReason,
  RecoveryGate,
  ReleaseProbeFenceRequest,
  ReleaseProbeFenceResult,
  W03HalfOpenProbeFenceAdapterOptions,
  W03LeaseExecutor,
  W03LeaseRow,
} from './types.js';
