export {
  applyRevenueLifecycleTransition,
  buildRevenueLifecycleEvent,
  createRevenueLifecycleRecord,
} from './lifecycle.js';
export {
  CONVERSATION_LIFECYCLE_STATES,
  CUSTOMER_LIFECYCLE_STATES,
  LEAD_LIFECYCLE_STATES,
  REVENUE_ENTITY_KINDS,
  REVENUE_LIFECYCLE_ERRORS,
  type ApplyRevenueLifecycleTransitionInput,
  type ApplyRevenueLifecycleTransitionResult,
  type ConversationLifecycleState,
  type CreateRevenueLifecycleInput,
  type CreateRevenueLifecycleResult,
  type CustomerLifecycleState,
  type LeadLifecycleState,
  type RevenueEntityKind,
  type RevenueEntityRef,
  type RevenueLifecycleChange,
  type RevenueLifecycleError,
  type RevenueLifecycleEvent,
  type RevenueLifecycleEventInput,
  type RevenueLifecycleLineage,
  type RevenueLifecycleMergeTarget,
  type RevenueLifecycleRecord,
  type RevenueLifecycleState,
  type RevenueLifecycleTransitionRecord,
  type RevenueProvenance,
} from './types.js';
