'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.TENANT_BOUNDARY_REASONS = exports.TENANT_BINDING_KINDS = void 0;
exports.TENANT_BINDING_KINDS = ['MEMBER', 'SYSTEM', 'EXTERNAL'];
exports.TENANT_BOUNDARY_REASONS = [
  'BOUNDARY_CONFIRMED',
  'TENANT_UNKNOWN',
  'IDENTITY_NOT_BOUND',
  'CROSS_TENANT_IDENTITY',
  'SUBJECT_MISMATCH',
  'EXTERNAL_IDENTITY_MISMATCH',
  'BINDING_KIND_MISMATCH',
  'BINDING_AMBIGUOUS',
];
