'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.POLICY_EVALUATION_REASONS =
  exports.POLICY_SNAPSHOT_STATES =
  exports.POLICY_EVALUATION_DECISIONS =
    void 0;
exports.POLICY_EVALUATION_DECISIONS = ['ALLOW', 'DENY', 'REQUIRE_APPROVAL'];
exports.POLICY_SNAPSHOT_STATES = ['ACTIVE', 'UNKNOWN'];
exports.POLICY_EVALUATION_REASONS = [
  'POLICY_ALLOWED',
  'APPROVAL_REQUIRED',
  'EXPLICIT_DENY',
  'NO_APPLICABLE_RULE',
  'CONFLICTING_RULES',
  'POLICY_STATE_UNKNOWN',
  'POLICY_VERSION_MISMATCH',
  'TENANT_BOUNDARY_DENIED',
  'ACTOR_NOT_ALLOWED',
  'SUBJECT_NOT_ALLOWED',
  'PURPOSE_DISABLED',
  'PURPOSE_MISMATCH',
  'CONSENT_REQUIRED',
  'CONSENT_EXPIRED',
  'CONSENT_REVOKED',
  'CONSENT_SUBJECT_MISMATCH',
  'CONSENT_JURISDICTION_MISMATCH',
  'CONSENT_PROVENANCE_MISSING',
  'JURISDICTION_DENIED',
  'DATA_CLASSIFICATION_NOT_ALLOWED',
  'AUTHORITY_REQUIRED',
  'AUTHORITY_EXPIRED',
  'AUTHORITY_REVOKED',
  'AUTHORITY_DENIED',
  'AUTHORITY_TENANT_MISMATCH',
  'AUTHORITY_ACTOR_MISMATCH',
  'AUTHORITY_SUBJECT_MISMATCH',
  'AUTHORITY_SCOPE_INSUFFICIENT',
  'AUTHORITY_ACTION_MISMATCH',
  'AUTHORITY_POLICY_MISMATCH',
  'AGENT_AUTHORITY_FORBIDDEN',
];
