'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.AUTHORITY_VALIDATION_REASONS = void 0;
/**
 * W02-E reasons describe authority-evidence validation only. Current-policy
 * reasons remain owned by W02-D and are composed through PolicyEvaluationReason.
 */
exports.AUTHORITY_VALIDATION_REASONS = [
  'MALFORMED_POLICY_TOKEN',
  'MALFORMED_SUBJECT_REFERENCE',
  'TOKEN_NOT_YET_VALID',
  'TOKEN_EXPIRED',
  'TOKEN_REVOKED',
  'TOKEN_STALE',
  'TOKEN_TENANT_MISMATCH',
  'TOKEN_SUBJECT_MISMATCH',
  'TOKEN_SCOPE_INSUFFICIENT',
  'TOKEN_ACTION_MISMATCH',
  'TOKEN_CONSTRAINT_VIOLATION',
  'TOKEN_POLICY_REFERENCE_MISMATCH',
  'TOKEN_POLICY_VERSION_MISMATCH',
  'TOKEN_CORRELATION_MISMATCH',
  'OWNER_DECISION_REQUIRED',
  'OWNER_DECISION_MALFORMED',
  'OWNER_DECISION_REFERENCE_MISMATCH',
  'OWNER_DECISION_NOT_YET_VALID',
  'OWNER_DECISION_EXPIRED',
  'OWNER_DECISION_DENIED',
  'OWNER_DECISION_REVOKED',
  'OWNER_DECISION_TENANT_MISMATCH',
  'OWNER_DECISION_ACTOR_MISMATCH',
  'OWNER_DECISION_SUBJECT_MISMATCH',
  'OWNER_DECISION_SCOPE_INSUFFICIENT',
  'OWNER_DECISION_CONSTRAINT_VIOLATION',
  'OWNER_DECISION_CORRELATION_MISMATCH',
  'AGENT_SELF_AUTHORIZATION_FORBIDDEN',
];
